name: Proxmox-Deploy-Lab

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"
          terraform_wrapper: false

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Terraform Apply
        env:
          # Ici, on fait le pont entre tes secrets GitHub (PM_...) 
          # et tes variables déclarées dans main.tf (proxmox_api_...)
          TF_VAR_proxmox_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_proxmox_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_proxmox_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
        run: |
          terraform init
          terraform apply -auto-approve
